# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardId', models.CharField(max_length=255)),
                ('maskNumber', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('bankId', models.CharField(max_length=255)),
                ('bankName', models.CharField(max_length=255)),
                ('cardFamilyName', models.CharField(max_length=255)),
                ('supportsInstallment', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('serviceProvider', models.CharField(max_length=255)),
                ('threeDSecureMandatory', models.CharField(max_length=255)),
                ('cvcMandatory', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IparaAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threeD', models.CharField(max_length=255)),
                ('orderId', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('echo', models.CharField(max_length=255)),
                ('cardOwnerName', models.CharField(max_length=255)),
                ('cardNumber', models.CharField(max_length=255)),
                ('cardExpireYear', models.CharField(max_length=255)),
                ('installment', models.CharField(max_length=255)),
                ('cvc', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('vendorId', models.CharField(max_length=255)),
                ('threeDSecureCode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('birthDate', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('tcCertificate', models.CharField(max_length=255)),
                ('clientIp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('tcCertificate', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('taxNumber', models.CharField(max_length=255)),
                ('taxOffice', models.CharField(max_length=255)),
                ('companyName', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='purchaser',
            name='invoiceAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiceAddress', to='main.PurchaserAddress'),
        ),
        migrations.AddField(
            model_name='purchaser',
            name='shippingAddress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shippingAddress', to='main.PurchaserAddress'),
        ),
        migrations.AddField(
            model_name='iparaauth',
            name='products',
            field=models.ManyToManyField(to='main.Product'),
        ),
        migrations.AddField(
            model_name='iparaauth',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Purchaser'),
        ),
    ]
